Fixes #131 Redirects admin to admin
eastlakehs/community-service-tracker pull request #178
Opened 2021-05-08 20:17 UTC by Zjjc123

Redirects admin to admin when in `/login` and in home page

2021-05-08 23:15 UTC, daniel-sudz submitted a review, later dismissed
Something similar for /table would be nice when an admin refreshes the page to go back to the dashboard 

![image](https://user-images.githubusercontent.com/52898838/117555946-988ccc80-b018-11eb-87d8-c4f8accc8d22.png)

2021-05-09 00:18 UTC, theTisch21 approved these changes
I can't test this (I'm not an admin), but it all looks good.

2021-05-09 00:48 UTC, daniel-sudz requested changes

2021-05-09 00:48 UTC, daniel-sudz commented on website/src/components/table/table.tsx
> +
could you move this to the controller that wraps the table component? The ```table.tsx``` should be a purely UI component

2021-05-09 01:27 UTC, daniel-sudz approved these changes
lgtm 👍

2021-05-09 01:51 UTC, merged